appName: "RWA Indexer Direct"

chain:
  chainId: 31337
  orderAddress: "0x5C7c905B505f0Cf40Ab6600d05e677F717916F6B" # OrderContract proxy address (deploy后替换)
  usdmAddress: "0x006EeA17e8DFb0b59B9208b2fAD1C791375fE17d" # USDM token address (deploy后替换)

rpcInfo:
  31337:
    rpcUrl: "http://127.0.0.1:8545"
    wssUrl: "ws://127.0.0.1:8545"
    nativeTokenSymbol: "ETH"
    nativeTokenDecimals: 18

db:
  host: "192.168.5.180"
  port: 5432
  username: "root"
  password: "root"
  database: "rwa"
  maxIdleConns: 20
  maxOpenConns: 200
  logLevel: 2
  sqlSlowThresholdMill: 10000
  migrationPath: "file://migrations/rwa"
  sslMode: "disable"

logger:
  level: "debug"
  encoderType: "console"
  outputType: "all"
  maxAge: 30
  enableColor: true

backend:
  privateKey: "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d" # Backend wallet private key,remove 0x (same as alpaca-stream, for cancelOrder on PlaceOrder failure)

alpaca:
  api_key: "PKDY3DRU4Z6EYNV5N632H3VBXZ"
  api_secret: "GJD6KZj6sbYKpUDSo1Gc77vhGaQyWqzM7abjGfyS4o57"
  base_url: "https://paper-api.alpaca.markets"
  data_url: "https://data.alpaca.markets"

kafka:
  enabled: true
  brokers:
    - "192.168.5.241:9092"
    - "192.168.5.242:9092"
    - "192.168.5.243:9092"
  orderUpdatePartitions: 3
  barPartitions: 3

indexer:
  pollInterval: 3
  batchSize: 100
  startBlock: 0
  confirmationBlocks: 0
