appName: "Reconciler"

db:
  host: "192.168.5.180"
  port: 5432
  username: "root"
  password: "root"
  database: "rwa"
  maxIdleConns: 20
  maxOpenConns: 200
  logLevel: 2
  sqlSlowThresholdMill: 10000
  migrationPath: "file://migrations/rwa"
  sslMode: "disable"

rpcInfo:
  31337:
    rpcUrl: "http://127.0.0.1:8545"
    wssUrl: "ws://127.0.0.1:8545"
    nativeTokenSymbol: "ETH"
    nativeTokenDecimals: 18

chain:
  chainId: 31337
  orderAddress: "0x5C7c905B505f0Cf40Ab6600d05e677F717916F6B"

backend:
  privateKey: "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

logger:
  level: "debug"
  encoderType: "console"
  outputType: "all"
  maxAge: 30
  enableColor: true
