appName: "RWA API"
server:
  port: 8000
  env : dev
  basePath : /api/v1
  apiKeys :
    - 099ba6fc-8da2-4d83-b3e9-a43813e471d3
  ginMode : debug

rpcInfo:
    97:
      rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545"
      wssUrl: "wss://bsc-testnet-rpc.publicnode.com"
      nativeTokenSymbol: BNB
      nativeTokenDecimals: 18

# chain config moved to indexer service

redis:
  hosts:
    - "127.0.0.1:6379"
  password: ""
  db: 0

db:
  host: "127.0.0.1"
  port: 5432
  username: "root"
  password: "root"
  database: "anchored"
  maxIdleConns: 20
  maxOpenConns: 200
  logLevel: 2
  sqlSlowThresholdMill: 10000
  migrationPath: "file://migrations/rwa"
  sslMode: "disable"

alpaca:
  api_key: "PKCO3XINYF5OEDNYX2QK76P7TL"
  api_secret: "H7JJw42qDoA6H1ETGa8DtvzKi7esneM1iaykzG1tXGrm"
  base_url: "https://paper-api.alpaca.markets"
  data_url: "https://data.alpaca.markets"
  
logger:
  level: "debug"
  encoderType: "console"
  outputType: "all"
  maxAge: 30
  enableColor: true

frontendTx:
  proxyWallet:
    mnemonic: "regret tumble escape crime open feature simple receive clog unaware window cruise"
    derivationPath: "m/44'/60'/0'/0"
  jwt:
    secret: "your-jwt-secret-key-change-in-production"
    expirationHours: 24